---
# Enter Your Variables for your workspace
vagrant_hostname: Sora
public_ssh_key: https://github.com/wieczoreko.keys
config_repo_url: git@github.com:wieczoreko/vagrant-ansible.git

vagrant_packages:
- curl
- wget
- vim
- htop
- git
- mc
- rsync
- zsh
