---
# Enter Your Variables for your workspace
vagrant_hostname: Sora
public_ssh_key: https://github.com/wieczoreko.keys
config_repo_url: https://github.com/wieczoreko/vagrant-ansible

vagrant_packages:
- curl
- wget
- vim
- htop
- git
- mc
- rsync
- zsh