---
- name: Download up-to-date Configuration Files
  become_user: vagrant
  git:
    repo: "{{ config_repo_url }}"
    dest: /home/vagrant/vagrant-ansible
  tags: UpdateGit

- name: Include Git Config
  include_tasks: git.yml
  tags: Deploy

- name: Include ZSH Config
  include_tasks: zsh.yml
  tags: Deploy

- name: Include Vim Config
  include_tasks: vim.yml
  tags: Deploy
