---
- name: Check if pathogen is installed
  stat: path={{ vagrant_home }}.vim
  register: pathogen

- name: Install pathogen"
  become_user: vagrant
  git:
    repo: "https://github.com/tpope/vim-pathogen"
    version: master
    depth: 1
    dest: "{{ vagrant_home }}/.vim"
  when: pathogen.stat.exists == False

- name: "Install plugins"
  become_user: vagrant
  git:
    repo: "{{ item.repo }}"
    version: "{{ item.version | default('master') }}"
    dest: "{{ vagrant_home }}/.vim/bundle/{{ item.name | default(item.repo.split('/')[-1][:-4]) }}"
    depth: 1
  with_items: "{{ pathogen_plugins }}"

- name: Copy Vim Config 
  template:
    src: templates/vimrc
    dest: "/home/vagrant/.vimrc"
    owner: vagrant

- name: "Infect .vimrc"
  lineinfile:
    line: "execute pathogen#infect()"
    dest: "{{ vagrant_home }}/.vimrc"

